/*
 * Exception.hpp
 *
 *  Created on: Nov 24, 2016
 *      Author: al1
 */

#ifndef SRC_WAYLAND_EXCEPTION_HPP_
#define SRC_WAYLAND_EXCEPTION_HPP_

#include <xen/be/Exception.hpp>

namespace Wayland {

/***************************************************************************//**
 * Exception generated by Wayland.
 * @ingroup wayland
 ******************************************************************************/
class Exception : public XenBackend::Exception
{
public:

	using XenBackend::Exception::Exception;
};

}

#endif /* SRC_WAYLAND_EXCEPTION_HPP_ */
