/*
 * Exception.hpp
 *
 *  Created on: Nov 24, 2016
 *      Author: al1
 */

#ifndef SRC_WAYLAND_EXCEPTION_HPP_
#define SRC_WAYLAND_EXCEPTION_HPP_

#include <string>

#include "DisplayItf.hpp"

namespace Wayland {

/***************************************************************************//**
 * Exception generated by Wayland.
 * @ingroup wayland
 ******************************************************************************/
class Exception : public DisplayItf::Exception
{
public:

	using DisplayItf::Exception::Exception;
};

}

#endif /* SRC_WAYLAND_EXCEPTION_HPP_ */
