/*
 * Exception.hpp
 *
 *  Created on: Nov 24, 2016
 *      Author: al1
 */

#ifndef SRC_WAYLAND_EXCEPTION_HPP_
#define SRC_WAYLAND_EXCEPTION_HPP_

#include <exception>
#include <string>

namespace Wayland {

/***************************************************************************//**
 * Exception generated by Drm.
 * @ingroup drm
 ******************************************************************************/
class WlException : public std::exception
{
public:
	/**
	 * @param msg error message
	 */
	explicit WlException(const std::string& msg) : mMsg(msg) {};

	/**
	 * returns error message
	 */
	const char* what() const throw() { return mMsg.c_str(); };

private:
	std::string mMsg;
};

}

#endif /* SRC_WAYLAND_EXCEPTION_HPP_ */
